copy setup.sqf func\client /Y
copy setup.sqf func\client\perFrame /Y
copy setup.sqf func\common /Y
copy setup.sqf func\common\net /Y
copy setup.sqf func\server /Y
copy setup.sqf fsms /Y
copy setup.sqf func /Y
copy setup.sqf scripts /Y
copy setup.sqf dialogs /Y